### ISSUE TITLE
テストCIの追加

### ISSUE THREAD

**Issue by bioerrorlog** [Japan-DfinityInfoHub/nft-barter#10]
# 概要・目的

開発を安全に進めるために、テストのCIを用意する

# AsIs
CIなし

# ToBe
GitHub Actionsで、PR時及びmain merge時に自動テストが走る

# タスク
- [ ] テストを実行するactions workflowを追加
- [ ] workflow粒度の検討

**Comment by hoosan** [comment]
Issue作成ありがとうございます🙏
外部依存をなるべく省くと最小構成こんな感じかなと思ってます：
 https://github.com/hoosan/auto-scaling-notes/blob/main/.github/workflows/e2e.yml

**Comment by bioerrorlog** [comment]
> 外部依存をなるべく省くと最小構成こんな感じ

vesselやdfxのインストールはコミュニティの肩に乗っかって、[aviate-labsのactions](https://github.com/aviate-labs/setup-dfx)を使っても良いかなと思うんですがどうですかね:

```yaml
      - uses:  aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: ${{ env.DFX_VERSION }}
          install-moc: true
          vessel-version: ${{ env.VESSEL_VERSION }}
```
